---

- name: Create Temp Directory
  shell: mkdir -p {{staging_dir}}

- name: Install wget & maven
  apt: name={{item}}
  with_items: 
  - wget
  - maven2

- name: Download YCSB Software
  shell: wget -qO {{staging_dir}}/ycsb.tgz {{ ycsb_tarball }}

- name: Extract files
  shell: tar -xvf {{staging_dir}}/ycsb.tgz --directory {{staging_dir}}

- name: Install YCSB
  command: chdir="{{staging_dir}}/ycsb-master" mvn package

- name: Configure databases.py
  template: src=databases.py.j2 dest={{staging_dir}}/ycsb-master/conf/databases.py

- name: Configure hosts.py
  template: src=hosts.py.j2 dest={{staging_dir}}/ycsb-master/conf/hosts.py

- name: Configure workloads.py
  template: src=workloads.py.j2 dest={{staging_dir}}/ycsb-master/conf/workloads.py

- name: Install YCSB client on client nodes
  shell: chdir="{{staging_dir}}/ycsb-master" yes | fab ycsb_deploy

- name: Begin load phase of YCSB
  command: chdir="{{staging_dir}}/ycsb-master" fab ycsb_load:db=aerospike
